export const products = [
    {
        age: "",
        body_html: "",
        collection_names: ["Spirits"],
        collection_slugs: ["spirits"],
        country: "",
        default_units_per_case: 12,
        gtc_slug: "waterford-single-farm-lakefield",
        gtc_variant: "UHJvZHVjdFZhcmlhbnQ6MzAyMA==",
        id: "7075783",
        image_srcset: null,
        image_thumbnail_100: null,
        image_thumbnail_250: null,
        image_thumbnail_500: null,
        in_stock: true,
        inventoried: true,
        on_sale_flag: false,
        on_sale_price: null,
        price_range_bucket: "$101 - 250",
        product_brand: "",
        product_category: "Spirits",
        product_category_slug: "spirits",
        product_id: 7075783,
        product_name: "Waterford Single Farm Lakefield",
        product_name_order: 8797116101114102,
        product_size: "700 mL",
        product_sku: "847718",
        product_subcategory: "Whisky",
        product_subsubcategory: "",
        qty_available: 3,
        rating: "",
        rating_numeric: "",
        region: "",
        retail_price: 104,
        retail_price_str: "104.00",
        short_description: "",
        store_id: 257,
        subregion: "",
        taxable: true,
        varietal: "",
        vintage: "",
        objectID: "7075783",
        text_match: 16737280,
        __position: 1,
    },
    {
        age: "",
        body_html: "",
        collection_names: ["Spirits"],
        collection_slugs: ["spirits"],
        country: "",
        default_units_per_case: 12,
        gtc_slug: "waterford-single-farm-hook-head",
        gtc_variant: "UHJvZHVjdFZhcmlhbnQ6NDIxOQ==",
        id: "7075761",
        image_srcset: null,
        image_thumbnail_100: null,
        image_thumbnail_250: null,
        image_thumbnail_500: null,
        in_stock: true,
        inventoried: true,
        on_sale_flag: false,
        on_sale_price: null,
        price_range_bucket: "$101 - 250",
        product_brand: "",
        product_category: "Spirits",
        product_category_slug: "spirits",
        product_id: 7075761,
        product_name: "Waterford Single Farm Hook Head",
        product_name_order: 8797116101114102,
        product_size: "700 mL",
        product_sku: "847717",
        product_subcategory: "Whisky",
        product_subsubcategory: "",
        qty_available: 3,
        rating: "",
        rating_numeric: "",
        region: "",
        retail_price: 104,
        retail_price_str: "104.00",
        short_description: "",
        store_id: 257,
        subregion: "",
        taxable: true,
        varietal: "",
        vintage: "",
        objectID: "7075761",
        text_match: 16737280,
        __position: 2,
    },
    {
        age: "",
        body_html: "",
        collection_names: ["Spirits"],
        collection_slugs: ["spirits"],
        country: "",
        default_units_per_case: 1,
        gtc_slug: "cotswolds-dry-gin",
        gtc_variant: "UHJvZHVjdFZhcmlhbnQ6MzMxOA==",
        id: "7055366",
        image_srcset: null,
        image_thumbnail_100: null,
        image_thumbnail_250: null,
        image_thumbnail_500: null,
        in_stock: true,
        inventoried: true,
        on_sale_flag: false,
        on_sale_price: null,
        price_range_bucket: "$51 - 100",
        product_brand: "",
        product_category: "Spirits",
        product_category_slug: "spirits",
        product_id: 7055366,
        product_name: "Cotswolds Dry Gin",
        product_name_order: 67111116115119110,
        product_size: "750ML",
        product_sku: "809791",
        product_subcategory: "Gin",
        product_subsubcategory: "",
        qty_available: 5,
        rating: "",
        rating_numeric: "",
        region: "",
        retail_price: 77,
        retail_price_str: "77.00",
        short_description: "",
        store_id: 257,
        subregion: "",
        taxable: true,
        varietal: "",
        vintage: "",
        objectID: "7055366",
        text_match: 16737280,
        __position: 3,
    },
    {
        age: "",
        body_html: "",
        collection_names: ["Spirits"],
        collection_slugs: ["spirits"],
        country: "",
        default_units_per_case: 12,
        gtc_slug: "dzama-rhum-de-madagascar-cuvee-blanche",
        gtc_variant: "UHJvZHVjdFZhcmlhbnQ6NTAyMA==",
        id: "7043735",
        image_srcset: null,
        image_thumbnail_100: null,
        image_thumbnail_250: null,
        image_thumbnail_500: null,
        in_stock: true,
        inventoried: true,
        on_sale_flag: false,
        on_sale_price: null,
        price_range_bucket: "0 - $50",
        product_brand: "",
        product_category: "Spirits",
        product_category_slug: "spirits",
        product_id: 7043735,
        product_name: "Dzama Rhum De Madagascar Cuvee Blanche",
        product_name_order: 68122971099732,
        product_size: "700 mL",
        product_sku: "760216",
        product_subcategory: "Rum",
        product_subsubcategory: "",
        qty_available: 12,
        rating: "",
        rating_numeric: "",
        region: "",
        retail_price: 46.6,
        retail_price_str: "46.60",
        short_description: "",
        store_id: 257,
        subregion: "",
        taxable: true,
        varietal: "",
        vintage: "",
        objectID: "7043735",
        text_match: 16737280,
        __position: 4,
    },
    {
        age: "",
        body_html: "",
        collection_names: ["Spirits"],
        collection_slugs: ["spirits"],
        country: "",
        default_units_per_case: 12,
        gtc_slug: "koloa-dark-rum",
        gtc_variant: "UHJvZHVjdFZhcmlhbnQ6NDU0OA==",
        id: "7043729",
        image_srcset: null,
        image_thumbnail_100: null,
        image_thumbnail_250: null,
        image_thumbnail_500: null,
        in_stock: true,
        inventoried: true,
        on_sale_flag: false,
        on_sale_price: null,
        price_range_bucket: "$51 - 100",
        product_brand: "",
        product_category: "Spirits",
        product_category_slug: "spirits",
        product_id: 7043729,
        product_name: "Koloa Dark Rum",
        product_name_order: 751111081119732,
        product_size: "750 mL",
        product_sku: "743400",
        product_subcategory: "Rum",
        product_subsubcategory: "",
        qty_available: 10,
        rating: "",
        rating_numeric: "",
        region: "",
        retail_price: 69.75,
        retail_price_str: "69.75",
        short_description: "",
        store_id: 257,
        subregion: "",
        taxable: true,
        varietal: "",
        vintage: "",
        objectID: "7043729",
        text_match: 16737280,
        __position: 5,
    },
    {
        age: "",
        body_html: "",
        collection_names: ["Spirits"],
        collection_slugs: ["spirits"],
        country: "",
        default_units_per_case: 6,
        gtc_slug: "hepburns-choice-ardmore",
        gtc_variant: "UHJvZHVjdFZhcmlhbnQ6MzMyOQ==",
        id: "7043689",
        image_srcset: null,
        image_thumbnail_100: null,
        image_thumbnail_250: null,
        image_thumbnail_500: null,
        in_stock: true,
        inventoried: true,
        on_sale_flag: false,
        on_sale_price: null,
        price_range_bucket: "$51 - 100",
        product_brand: "",
        product_category: "Spirits",
        product_category_slug: "spirits",
        product_id: 7043689,
        product_name: "Hepburn's Choice Ardmore",
        product_name_order: 7210111298117114,
        product_size: "700 mL",
        product_sku: "843446",
        product_subcategory: "Whisky",
        product_subsubcategory: "",
        qty_available: 4,
        rating: "",
        rating_numeric: "",
        region: "",
        retail_price: 98.85,
        retail_price_str: "98.85",
        short_description: "",
        store_id: 257,
        subregion: "",
        taxable: true,
        varietal: "",
        vintage: "",
        objectID: "7043689",
        text_match: 16737280,
        __position: 6,
    },
    {
        age: "",
        body_html: "",
        collection_names: ["Spirits"],
        collection_slugs: ["spirits"],
        country: "",
        default_units_per_case: 1,
        gtc_slug: "bard-cinder-and-smoke-bourbon",
        gtc_variant: "UHJvZHVjdFZhcmlhbnQ6MzM2MQ==",
        id: "6989672",
        image_srcset: null,
        image_thumbnail_100: null,
        image_thumbnail_250: null,
        image_thumbnail_500: null,
        in_stock: true,
        inventoried: true,
        on_sale_flag: false,
        on_sale_price: null,
        price_range_bucket: "$101 - 250",
        product_brand: "",
        product_category: "Spirits",
        product_category_slug: "spirits",
        product_id: 6989672,
        product_name: "Bard Cinder and Smoke Bourbon",
        product_name_order: 66971141003267,
        product_size: "750 mL",
        product_sku: "847443",
        product_subcategory: "Whisky USA",
        product_subsubcategory: "",
        qty_available: 2,
        rating: "",
        rating_numeric: "",
        region: "",
        retail_price: 178.8,
        retail_price_str: "178.80",
        short_description: "",
        store_id: 257,
        subregion: "",
        taxable: true,
        varietal: "",
        vintage: "",
        objectID: "6989672",
        text_match: 16737280,
        __position: 7,
    },
    {
        age: "",
        body_html: "",
        collection_names: ["Spirits"],
        collection_slugs: ["spirits"],
        country: "",
        default_units_per_case: 6,
        gtc_slug: "rum-dos-maderas-55-px",
        gtc_variant: "UHJvZHVjdFZhcmlhbnQ6MzI5MA==",
        id: "6989419",
        image_srcset: null,
        image_thumbnail_100: null,
        image_thumbnail_250: null,
        image_thumbnail_500: null,
        in_stock: true,
        inventoried: true,
        on_sale_flag: false,
        on_sale_price: null,
        price_range_bucket: "$51 - 100",
        product_brand: "",
        product_category: "Spirits",
        product_category_slug: "spirits",
        product_id: 6989419,
        product_name: "Rum Dos Maderas 5+5 PX",
        product_name_order: 821171093268111,
        product_size: "700 mL",
        product_sku: "742865",
        product_subcategory: "Rum",
        product_subsubcategory: "",
        qty_available: 5,
        rating: "",
        rating_numeric: "",
        region: "",
        retail_price: 66.45,
        retail_price_str: "66.45",
        short_description: "",
        store_id: 257,
        subregion: "",
        taxable: true,
        varietal: "",
        vintage: "",
        objectID: "6989419",
        text_match: 16737280,
        __position: 8,
    },
    {
        age: "",
        body_html: "",
        collection_names: ["Spirits"],
        collection_slugs: ["spirits"],
        country: "",
        default_units_per_case: 6,
        gtc_slug: "six-saints-rum",
        gtc_variant: "UHJvZHVjdFZhcmlhbnQ6MzI5MQ==",
        id: "6989418",
        image_srcset: null,
        image_thumbnail_100: null,
        image_thumbnail_250: null,
        image_thumbnail_500: null,
        in_stock: true,
        inventoried: true,
        on_sale_flag: false,
        on_sale_price: null,
        price_range_bucket: "$51 - 100",
        product_brand: "",
        product_category: "Spirits",
        product_category_slug: "spirits",
        product_id: 6989418,
        product_name: "Six Saints Rum",
        product_name_order: 83105120328397,
        product_size: "700 mL",
        product_sku: "786892",
        product_subcategory: "Rum",
        product_subsubcategory: "",
        qty_available: 6,
        rating: "",
        rating_numeric: "",
        region: "",
        retail_price: 67.15,
        retail_price_str: "67.15",
        short_description: "",
        store_id: 257,
        subregion: "",
        taxable: true,
        varietal: "",
        vintage: "",
        objectID: "6989418",
        text_match: 16737280,
        __position: 9,
    },
    {
        age: "",
        body_html: "",
        collection_names: ["Spirits"],
        collection_slugs: ["spirits"],
        country: "",
        default_units_per_case: 6,
        gtc_slug: "malecon-rare-proof-20-year",
        gtc_variant: "UHJvZHVjdFZhcmlhbnQ6NDc0NQ==",
        id: "6989408",
        image_srcset: null,
        image_thumbnail_100: null,
        image_thumbnail_250: null,
        image_thumbnail_500: null,
        in_stock: true,
        inventoried: true,
        on_sale_flag: false,
        on_sale_price: null,
        price_range_bucket: "$101 - 250",
        product_brand: "",
        product_category: "Spirits",
        product_category_slug: "spirits",
        product_id: 6989408,
        product_name: "Malecon Rare Proof 20 Year",
        product_name_order: 779710810199111,
        product_size: "700 mL",
        product_sku: "807976",
        product_subcategory: "Rum",
        product_subsubcategory: "",
        qty_available: 5,
        rating: "",
        rating_numeric: "",
        region: "",
        retail_price: 109.35,
        retail_price_str: "109.35",
        short_description: "",
        store_id: 257,
        subregion: "",
        taxable: true,
        varietal: "",
        vintage: "",
        objectID: "6989408",
        text_match: 16737280,
        __position: 10,
    },
];
